#!/bin/bash

cr_dir=$(touch testfile{1..10})
echo $cr_dir


#user=lekner
#if grep $user /etc/passwd
#then
#echo "The $user Exist"
#fi




#if pwd
#then
#echo "it works"
#fi



#var1=$((5 + 5))
#echo $var1
#var2=$(($var1 * 2))
#echo $var2
#mydir=$(pwd)
#echo $mydir
#grade=5
#person="Adam"
#money=10
#echo "$person is a good boy, he is in grade $grade.Also he had $money \$ in his pocket"


